CREATE DATABASE estudiantes_temp;
ALTER DATABASE estudiantes_temp RENAME TO estudiantes;
DROP DATABASE estudiantes;
SHOW DATABASES;
USE DATABASE estudiantes;
CREATE TABLE estudiante(id INT, nombre CHAR(25), edad INT, CONSTRAINT PRIMARY KEY(id), CONSTRAINT edad_check CHECK(edad > 25));
CREATE TABLE estudiante(id INT, nombre CHAR(25) DEFAULT 'Juanito', edad INT DEFAULT 10, CONSTRAINT PRIMARY KEY(id), CONSTRAINT edad_check CHECK(edad > 25));
ALTER TABLE estudiante RENAME TO estudiante_2;
ALTER TABLE estudiante ADD COLUMN carnet CHAR(25);
DROP TABLE estudiante;
SHOW TABLES;
SHOW COLUMNS FROM estudiante;
SELECT * FROM estudiante WHERE edad > 25;
INSERT INTO estudiante (columna_a, columna_b) VALUES ('A', 'B');
INSERT INTO estudiante VALUES ('A', 'B');
INSERT INTO estudiante VALUES (-120, -1, 0, 15, 1000, 1.0, 0.0, '2018-04-01');
UPDATE estudiante SET nombre = 'Juan' WHERE nombre = 'Pedro';
DELETE FROM estudiante WHERE nombre = 'Pedro';
SELECT nombre FROM estudiante WHERE nombre = 'Pedro' ORDER BY DESC;
SELECT nombre FROM estudiante, profesor WHERE nombre = 'Pedro' ORDER BY DESC;
SELECT nombre FROM estudiante LEFT JOIN profesor ON estudiante.profesor_id = profesor.id WHERE estudiante.nombre = 'Pedro' ORDER BY DESC;
SELECT nombre FROM estudiante INNER JOIN profesor ON estudiante.profesor_id = profesor.id WHERE estudiante.nombre = 'Pedro' ORDER BY DESC;
SELECT nombre FROM estudiante WHERE nombre IS NULL;
SELECT nombre FROM estudiante WHERE nombre IS NOT NULL;
SELECT COUNT(id) FROM estudiante GROUP BY edad;
